# Generated by Django 2.2.12 on 2020-04-25 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('call_no', models.AutoField(primary_key=True, serialize=False)),
                ('time_of_call', models.DateField()),
                ('recording', models.CharField(max_length=25)),
                ('willingness_to_buy', models.CharField(max_length=25)),
                ('notes', models.CharField(max_length=25)),
                ('schedule_call_back', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Close',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('product_no', models.CharField(max_length=25)),
                ('credit_card_no', models.CharField(max_length=25)),
                ('billing_address', models.CharField(max_length=25)),
                ('shipping_address', models.CharField(max_length=25)),
                ('invoice_no', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Qualify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=25)),
                ('sex', models.CharField(max_length=25)),
                ('martial_status', models.BooleanField(default=False)),
                ('occupation', models.CharField(max_length=25)),
                ('role', models.CharField(max_length=25)),
                ('budget', models.CharField(max_length=25)),
                ('time_of_call', models.DateField()),
                ('qualified', models.BooleanField(default=False)),
                ('notes', models.CharField(max_length=25)),
                ('recording', models.CharField(max_length=25)),
                ('schedule_call_back', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('lead_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=25)),
                ('role', models.CharField(max_length=25)),
                ('time', models.DateField()),
                ('qualifed', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Qualify')),
                ('sales_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Call')),
            ],
        ),
        migrations.AddField(
            model_name='call',
            name='close',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Close'),
        ),
    ]
